### ISSUE TITLE
Missing parameters

### ISSUE THREAD

**Issue by xocasdashdash** [neithanmo/fluent-bit-rs#4]
Hey!

I'm looking to use this project to build and output plugin in rust. I think I've found an issue where you can't really read any configuration for the plugin. Also, the tag is missing from the Flush call (or it looks like this on a first read). 

Rust is not a language I feel comfortable in, Is there any reason all this hasn't been implemented? It could be that I'm missing something but I'd appreciate your support

**Comment by neithanmo** [comment]
Hi @xocasdashdash  
I am not sure if I understood the issue. so, can you elaborate a bit more about "can't really read any configuration for the plugin", read from where? , about the tag, yes, It has not been exposed through the public api yet, but, It should be easy to add, do you want to collaborate with it? I can help you if You want. If that is not the case, I can add support for it maybe next weekend.. :)

**Comment by xocasdashdash** [comment]
well, in fluent bit you can load configuration for a specific plugin. 
You can see how its done here for go:
https://github.com/fluent/fluent-bit-go/blob/master/examples/out_gstdout/out_gstdout.go#L19-L24

I have very little experience with Rust, this is one of the reasons why I want to do this little side project

**Comment by neithanmo** [comment]
Thank you for the link,  it clarifies a lot. those features don't look difficult to implement, the easiest one is the tag in the flush function.
I will add these features next days and will inform you here once it is ready for testing.

**Comment by neithanmo** [comment]
The tag feature was added, It is in the dev branch if you want to test. also updated the examples/json example to use it.. still need to add the configuration feature, once It is done, I will submit this as fluent-bit v0.2., because It will be a breaking change.

**Comment by neithanmo** [comment]
About the configuration, and don't see if it is necessary, considering that you can have a context in your struct or whatever you implement the trait FLBPluginMethods on, as far as I understand, this configuration is a sort of global variable or state??
https://github.com/fluent/fluent-bit-go/blob/e125cab1796300900f5f496c413270b58002309f/output/output.go#L72
, so, by implementing this Trait on a struct, in the init function you can initialize and configure any context your implementor has, let's say you can initialize custom buffers, parsers or even make http requests etc.. What would be common use for this context initialization in go, what would you usually do with this??

**Comment by xocasdashdash** [comment]
Yeah, the configuration could be used to pass parameters down to the output plugin. If you check out any of the "normal" output plugins from fluent-bit you can see that they're very configurable.

In the usecase I'm thinking I'd use to configure the location of an http client cert, the destination URL and some more parameters. 

The code you're linking what I think it does is generate a unique ID per copy of the output plugin. I'm guessing in order to namespace the configuration of each copy.

**Comment by neithanmo** [comment]
Hi:
It is done, you can check the dev branch.
you can follow the example in examples/json to see how it works. 
Please tell me how it goes on your side, once the example is compiled, I ran it using:

`fluent-bit -e libjson.so -i cpu -o "rustout" --prop="params=http://example.com"`

**Comment by xocasdashdash** [comment]
Hey! Sorry I didn't get back to you, i did manage to get a simple example working. Thanks for implementing it!
